- src/main/java/org/verapdf/as/ASAtom.java
- src/main/java/org/verapdf/as/filters/ASFilterFactory.java
- src/main/java/org/verapdf/as/filters/ASInFilter.java
- src/main/java/org/verapdf/as/io/ASFileInStream.java
- src/main/java/org/verapdf/as/io/ASInputStream.java
- src/main/java/org/verapdf/cos/COSName.java
- src/main/java/org/verapdf/font/cmap/CMapFile.java
- src/main/java/org/verapdf/io/ASMemoryInStream.java
- src/main/java/org/verapdf/io/InternalInputStream.java
- src/main/java/org/verapdf/parser/BaseParser.java
- src/main/java/org/verapdf/parser/COSParser.java
- src/main/java/org/verapdf/parser/PDFParser.java
- src/main/java/org/verapdf/parser/PDFStreamParser.java
- src/main/java/org/verapdf/pd/PDContentStream.java
- src/main/java/org/verapdf/pd/PDPageContentStream.java
> ASInput stream is an abstract class extending java InputStream now.

- .travis.yml
- added .travis.yml based on library version.
> FEAT - Travis build

- src/main/java/org/verapdf/pd/font/PDCIDFont.java
- src/main/java/org/verapdf/pd/font/PDFont.java
- src/main/java/org/verapdf/pd/font/truetype/PDTrueTypeFont.java
- src/main/java/org/verapdf/pd/font/truetype/TrueTypeBaseParser.java
- src/main/java/org/verapdf/pd/font/truetype/TrueTypeFontParser.java
- src/main/java/org/verapdf/pd/font/truetype/TrueTypeHeadTable.java
- src/main/java/org/verapdf/pd/font/truetype/TrueTypeMaxpTable.java
- src/main/java/org/verapdf/pd/font/truetype/TrueTypeTable.java
- src/main/java/org/verapdf/pd/font/type1/PDType1Font.java
> Fixed multiple font program parsing.

- pom.xml
- bumped minor -> 0.3 for development.
> DEV - Development version 0.3

- src/main/java/org/verapdf/cos/COSBody.java
- src/main/java/org/verapdf/cos/COSDictionary.java
- src/main/java/org/verapdf/cos/COSFilters.java
- src/main/java/org/verapdf/cos/COSObject.java
- src/main/java/org/verapdf/cos/COSString.java
- src/main/java/org/verapdf/cos/visitor/Writer.java
- src/main/java/org/verapdf/parser/COSParser.java
- src/main/java/org/verapdf/parser/DecodedObjectStreamParser.java
- src/main/java/org/verapdf/parser/PDFParser.java
- src/main/java/org/verapdf/parser/PDFStreamParser.java
- src/main/java/org/verapdf/parser/Token.java
- src/main/java/org/verapdf/pd/encryption/StandardSecurityHandler.java
- src/main/java/org/verapdf/pd/font/cff/CFFFontProgram.java
Also fixed integration test results.
> Cosstring refact

- pom.xml
- bumped minor -> 0.5 for development.
> DEV - Development version 0.5

- src/main/java/org/verapdf/pd/font/Encoding.java
- src/main/java/org/verapdf/pd/font/cmap/CMap.java
closes https://github.com/veraPDF/veraPDF-library/issues/677.
closes https://github.com/veraPDF/veraPDF-library/issues/674.
> Fixed two issues.

- src/main/java/org/verapdf/cos/COSString.java
- src/main/java/org/verapdf/cos/visitor/Writer.java
Closes veraPDF/veraPDF-library#680.
> Fixed COSString printing in writer.

- src/main/java/org/verapdf/as/io/ASInputStream.java
- src/main/java/org/verapdf/as/io/ASInputStreamWrapper.java
- src/main/java/org/verapdf/io/InternalInputStream.java
- src/main/java/org/verapdf/io/Reader.java
- src/main/java/org/verapdf/parser/COSParser.java
- src/main/java/org/verapdf/parser/PDFParser.java
- src/main/java/org/verapdf/pd/font/Encoding.java
- src/main/java/org/verapdf/pd/font/truetype/AdobeGlyphList.java
- src/main/java/org/verapdf/pd/font/truetype/TrueTypeFontProgram.java
- src/main/java/org/verapdf/pd/font/truetype/TrueTypePredefined.java
- src/main/java/org/verapdf/pd/font/type1/EexecFilterDecode.java
Closes https://github.com/veraPDF/veraPDF-library/issues/678.
> Fix branch

- src/main/java/org/verapdf/as/filters/io/ASBufferingInFilter.java
- src/main/java/org/verapdf/cos/filters/COSFilterFlateDecode.java
- src/main/java/org/verapdf/cos/filters/COSFilterRC4DecryptionDefault.java
Closes https://verapdf.atlassian.net/browse/PT-475.
> Fixed skipping in COSFilters.

- src/main/java/org/verapdf/pd/font/PDCIDFont.java
closes veraPDF/veraPDF-parser#186
> Fixed default width value.

- src/main/java/org/verapdf/pd/font/cmap/PDCMap.java
- src/main/java/org/verapdf/pd/font/truetype/TrueTypeCmapTable.java
Closes veraPDF/veraPDF-library#708.
> CMap caching fixed. CMap parsing fixed.

- src/main/java/org/verapdf/parser/BaseParser.java
- src/main/java/org/verapdf/parser/PDFStreamParser.java
Closes veraPDF/veraPDF-parser#192.
> Added delimeter character check to operator parser.

- pom.xml
- bumped minor -> 1.3 for development.
> DEV - Development version 1.3

- .travis.yml
- README.md
- pom.xml
- bumped minor to 1.4 for release;
- got ready for Maven central publishing;
- added test coverage publication;
- updated README build instructions; and
- updated README badges.
> REL - Release v1.4

- .travis.yml
- README.md
- pom.xml
- bumped minor -> 1.5 for development.
> DEV - Development 1.5

- src/main/java/org/verapdf/pd/font/cff/CFFCIDFontProgram.java
- src/main/java/org/verapdf/pd/font/cff/CFFType1FontProgram.java
- src/main/java/org/verapdf/pd/font/type1/Type1FontProgram.java
Closes https://github.com/veraPDF/veraPDF-parser/issues/226.
> ArrayIndexOutOfBoundsException fixes.

- src/main/java/org/verapdf/io/Reader.java
- src/main/java/org/verapdf/parser/PDFParser.java
Closes https://github.com/veraPDF/veraPDF-apps/issues/202
> Fixed ID obtaining for document decryption.

- src/main/java/org/verapdf/pd/colors/PDDeviceN.java
- src/main/java/org/verapdf/pd/colors/PDIndexed.java
- src/main/java/org/verapdf/pd/colors/PDSeparation.java
- src/main/java/org/verapdf/pd/colors/PDSpecialColorSpace.java
> Fixed stack overflow error in case of looped alternate colorspace

- pom.xml
- bumped minor -> 1.7 for development.
> REL - Development version v1.7

- src/main/java/org/verapdf/cos/visitor/Writer.java
Closes https://github.com/veraPDF/veraPDF-parser/issues/238
> Fixed error in metadata fixing.

- src/main/java/org/verapdf/pd/font/truetype/TrueTypeFontProgram.java
- src/main/java/org/verapdf/pd/font/truetype/TrueTypePostTable.java
Closes https://github.com/veraPDF/veraPDF-library/issues/762.
> Added post table to true type encoding process.

- src/main/java/org/verapdf/pd/PDExtGState.java
> Fixed ExtGState OP key handling.

- src/main/java/org/verapdf/pd/structure/PDNumberTreeNode.java
fixes loop-7.pdf from https://github.com/veraPDF/veraPDF-library/issues/821
> Added detecting of loops in number tree

- src/main/java/org/verapdf/pd/PDNameTreeNode.java
- src/main/java/org/verapdf/pd/form/PDFormField.java
- src/main/java/org/verapdf/pd/form/PDSignatureField.java
Fixes loop-2.pdf and loop-6.pdf from https://github.com/veraPDF/veraPDF-library/issues/821
> Added detection of loops in name trees and form fields

- src/main/java/org/verapdf/cos/COSDocument.java
- src/main/java/org/verapdf/cos/COSStream.java
- src/main/java/org/verapdf/exceptions/LoopedException.java
- src/main/java/org/verapdf/pd/PDNameTreeNode.java
- src/main/java/org/verapdf/pd/PDPage.java
- src/main/java/org/verapdf/pd/PDPageTreeBranch.java
- src/main/java/org/verapdf/pd/form/PDFormField.java
- src/main/java/org/verapdf/pd/structure/PDNumberTreeNode.java
Closes https://github.com/veraPDF/veraPDF-library/issues/843.
> Fixed loop in getting object from reader.

- src/main/java/org/verapdf/pd/PDObject.java
Closes https://github.com/veraPDF/veraPDF-library/issues/852.
> Fixed nullpointerexception.

- src/main/java/org/verapdf/parser/BaseParser.java
- src/main/java/org/verapdf/parser/Token.java
Closes https://github.com/veraPDF/veraPDF-library/issues/861
> Added ASCII85 strings parsing.

- src/main/java/org/verapdf/parser/BaseParser.java
- src/main/java/org/verapdf/pd/font/type1/Type1FontProgram.java
- src/main/java/org/verapdf/pd/font/type1/Type1PrivateParser.java
Closes https://github.com/veraPDF/veraPDF-library/issues/862.
> Fixed PostScript name parsing in Type1 font program.

- src/main/java/org/verapdf/pd/font/cff/Type2CharStringParser.java
- src/main/java/org/verapdf/pd/font/type1/BaseCharStringParser.java
Closes https://github.com/veraPDF/veraPDF-library/issues/867
Closes https://github.com/veraPDF/veraPDF-library/issues/868
> Fixed Type2 charstring parsing bug

- pom.xml
- bumped minor -> 1.8 for release.
> REL - Release v1.8

- src/main/java/org/verapdf/as/filters/ASInFilter.java
- src/main/java/org/verapdf/as/filters/io/ASBufferedInFilter.java
- src/main/java/org/verapdf/as/io/ASFileInStream.java
- src/main/java/org/verapdf/as/io/ASInputStream.java
- src/main/java/org/verapdf/as/io/ASInputStreamWrapper.java
- src/main/java/org/verapdf/as/io/ASMemoryInStream.java
- src/main/java/org/verapdf/cos/COSStream.java
- src/main/java/org/verapdf/io/InternalInputStream.java
- src/main/java/org/verapdf/io/Reader.java
- src/main/java/org/verapdf/io/SeekableInputStream.java
- src/main/java/org/verapdf/parser/NotSeekableBaseParser.java
- src/main/java/org/verapdf/pd/PDPage.java
- src/main/java/org/verapdf/pd/encryption/StandardSecurityHandler.java
- src/main/java/org/verapdf/pd/font/type1/Type1FontProgram.java
- src/main/java/org/verapdf/pd/font/type1/Type1PrivateParser.java
Closes https://github.com/veraPDF/veraPDF-apps/issues/218
> Fixed resource leaking

- src/main/java/org/verapdf/parser/NotSeekableBaseParser.java
- src/main/java/org/verapdf/parser/NotSeekableCOSParser.java
- src/main/java/org/verapdf/parser/Token.java
- src/main/java/org/verapdf/parser/postscript/PSLiteralObject.java
- src/main/java/org/verapdf/parser/postscript/PSObject.java
- src/main/java/org/verapdf/parser/postscript/PSOperator.java
- src/main/java/org/verapdf/parser/postscript/PSParser.java
- src/main/java/org/verapdf/parser/postscript/PSProcedure.java
- src/main/java/org/verapdf/parser/postscript/PSStackMark.java
- src/main/java/org/verapdf/parser/postscript/PostScriptException.java
- src/main/java/org/verapdf/pd/font/cmap/CMapFactory.java
- src/main/java/org/verapdf/pd/font/cmap/CMapParser.java
- src/test/java/org/verapdf/pd/font/cmap/CMapTest.java
Closes https://github.com/veraPDF/veraPDF-library/issues/838
> PostScript parser added for CMap parsing

- src/main/java/org/verapdf/cos/filters/COSFilterASCII85Decode.java
- src/main/java/org/verapdf/pd/font/type1/Type1FontProgram.java
Closes https://github.com/veraPDF/veraPDF-library/issues/866
> Fixed ASCII85 parsing.

- src/main/java/org/verapdf/pd/font/cmap/CMapParser.java
Closes https://github.com/veraPDF/veraPDF-library/issues/908
> Usecmap bug fixed.

- src/main/java/org/verapdf/pd/font/stdmetrics/StandardFontMetricsFactory.java
More robust and portable way of loading an AFM file. Works for local files and virtual file locations like jar: or vfs:
> Fix issue 312

- src/main/java/org/verapdf/as/filters/io/ASBufferedInFilter.java
- src/main/java/org/verapdf/io/InternalInputStream.java
- src/main/java/org/verapdf/io/SeekableInputStream.java
- src/main/java/org/verapdf/parser/NotSeekableBaseParser.java
- src/main/java/org/verapdf/pd/font/cff/Type2CharStringParser.java
- src/main/java/org/verapdf/pd/font/cmap/PDCMap.java
- src/main/java/org/verapdf/pd/font/stdmetrics/StandardFontMetricsFactory.java
- src/main/java/org/verapdf/pd/font/truetype/AdobeGlyphList.java
- src/main/java/org/verapdf/pd/font/type1/BaseCharStringParser.java
closes https://github.com/veraPDF/veraPDF-parser/issues/324
> Font programs parsing fix. Temp files generation fix

- src/main/java/org/verapdf/parser/BaseParser.java
closes https://github.com/veraPDF/veraPDF-library/issues/930
> Fixed base parser skip comment method

- src/main/java/org/verapdf/as/filters/io/ASBufferedInFilter.java
closes https://github.com/veraPDF/veraPDF-parser/issues/331
> Fixed reading for buffered in filter

- src/main/java/org/verapdf/parser/postscript/PSOperator.java
closes https://github.com/veraPDF/veraPDF-parser/issues/339
> Fixed issue with unseen Standard Encoding in PS font program

- src/main/java/org/verapdf/parser/PDFParser.java
- src/main/java/org/verapdf/parser/SignatureParser.java
closes https://github.com/veraPDF/veraPDF-library/issues/943
> Signatures parsing fixes

- src/main/java/org/verapdf/pd/font/type1/PDType1Font.java
- src/main/java/org/verapdf/pd/images/PDInlineImage.java
closes https://github.com/veraPDF/veraPDF-library/issues/946
> Type 1 font isStandard fix

- src/main/java/org/verapdf/parser/BaseParser.java
- src/main/java/org/verapdf/pd/font/CIDToGIDMapping.java
- src/main/java/org/verapdf/pd/font/cff/CFFFileBaseParser.java
- src/main/java/org/verapdf/pd/font/opentype/OpenTypeFontProgram.java
- src/main/java/org/verapdf/pd/font/truetype/TrueTypeBaseParser.java
closes https://github.com/veraPDF/veraPDF-library/issues/942
> Added stream closing

- src/main/java/org/verapdf/parser/SignatureParser.java
closes https://github.com/veraPDF/veraPDF-library/issues/917
> Fixed wrong behaviour with signature EOF in stream logic

- src/main/java/org/verapdf/pd/font/PDCIDFont.java
- src/main/java/org/verapdf/pd/font/cff/CFFFileBaseParser.java
- src/main/java/org/verapdf/pd/font/cff/CFFFontProgram.java
- src/main/java/org/verapdf/pd/font/cmap/CMapFile.java
- src/main/java/org/verapdf/pd/font/opentype/OpenTypeFontProgram.java
- src/main/java/org/verapdf/pd/font/type1/PDType1Font.java
closes https://github.com/veraPDF/veraPDF-library/issues/959
> Added stream closing for cff fonts and cmaps

- src/main/java/org/verapdf/factory/colors/ColorSpaceFactory.java
- src/main/java/org/verapdf/tools/TypeConverter.java
closes https://github.com/veraPDF/veraPDF-library/issues/979
> Fixed SOF exception for colorspaces, fixed date parser

- src/main/java/org/verapdf/pd/font/PDCIDFont.java
- src/main/java/org/verapdf/pd/font/truetype/PDTrueTypeFont.java
- src/main/java/org/verapdf/pd/font/type1/PDType1Font.java
- src/main/java/org/verapdf/pd/font/type1/Type1PrivateParser.java
- src/main/java/org/verapdf/pd/font/type1/Type1StringConstants.java
- src/main/java/org/verapdf/tools/FontProgramIDGenerator.java
closes https://github.com/veraPDF/veraPDF-library/issues/981
> Added warnings for invalid subtype for fontfile3, fixed font program caching

- src/main/java/org/verapdf/as/ASAtom.java
- src/main/java/org/verapdf/parser/FunctionParser.java
- src/main/java/org/verapdf/pd/PDExtGState.java
- src/main/java/org/verapdf/pd/PDHalftone.java
- src/main/java/org/verapdf/pd/colors/PDDeviceN.java
- src/main/java/org/verapdf/pd/colors/PDSeparation.java
- src/main/java/org/verapdf/pd/function/PDFunction.java
- src/main/java/org/verapdf/pd/function/PDType3Function.java
Added function parser for parsing PDFunction elements.
> Implementation limits and Type 4 functions #795

- src/main/java/org/verapdf/pd/colors/PDICCBased.java
- src/main/java/org/verapdf/tools/StaticResources.java
> Add method getICCProfileIndirect to PDICCBased 

- pom.xml
- bumped minor version to 1.18; and
- using parent POM v1.18.1
>  REL - veraPDF v1.18

- src/main/java/org/verapdf/pd/font/type1/Type1PrivateParser.java
Fix case with wrong charstring amount
> Fix parsing type1 font program private part

- pom.xml
- bumped minor version to 1.20
> REL - Release v1.20

- src/main/java/org/verapdf/pd/images/PDInlineImage.java
https://www.pdfa.org/safedocs-unearths-pdf-inline-image-issue/
> Fix isInterpolate and getCOSFilters in PDInlineImage

- src/main/java/org/verapdf/pd/encryption/PDEncryption.java
- src/main/java/org/verapdf/pd/font/cmap/CMapParser.java
> Fix NullPointerException and IndexOutOfBoundsException

- src/main/java/org/verapdf/io/Reader.java
> Fix closing resources in Reader

- README.md
- pom.xml
- bumped minor version to 1.24
- updated readme
> REL - Release v1.24

- pom.xml
> DEV: v1.25

- src/main/java/org/verapdf/as/io/ASMemoryInStream.java
- src/main/java/org/verapdf/cos/filters/COSFilterRegistry.java
- src/main/java/org/verapdf/io/InternalInputStream.java
- src/main/java/org/verapdf/io/Reader.java
- src/main/java/org/verapdf/io/SeekableInputStream.java
- src/main/java/org/verapdf/parser/BaseParser.java
- src/main/java/org/verapdf/parser/COSParser.java
- src/main/java/org/verapdf/parser/DecodedObjectStreamParser.java
- src/main/java/org/verapdf/parser/FunctionParser.java
- src/main/java/org/verapdf/parser/NotSeekableCOSParser.java
- src/main/java/org/verapdf/parser/PDFParser.java
- src/main/java/org/verapdf/parser/SignatureParser.java
- src/main/java/org/verapdf/pd/PDPageTreeBranch.java
- src/main/java/org/verapdf/pd/font/stdmetrics/AFMParser.java
- src/main/java/org/verapdf/pd/font/type1/Type1PrivateParser.java
> Add warning for duplicated keys

- src/main/java/org/verapdf/pd/font/cff/CFFType1FontProgram.java
> Add warning about duplicated glyph name

- README.md
- pom.xml
- bumped minor version to 1.26
- update parent version to 1.26.2
> REL - v1.26

- src/main/java/org/verapdf/tools/TaggedPDFHelper.java
Add isCircularMappingExist to TaggedPDFHelper
> Fix getRoleMapToSameNamespaceTag method in TaggedPDFHelper.

- README.md
- pom.xml
- bumped minor version to 1.28
- updated readme
> REL - v1.28
